{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"users.findFirst","timestamp":"2024-07-02T13:20:27.279Z"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"users.findFirst","timestamp":"2024-07-02T13:20:33.987Z"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"users.findFirst","timestamp":"2024-07-02T13:20:50.158Z"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"users.findFirst","timestamp":"2024-07-02T13:21:17.926Z"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"users.findFirst","timestamp":"2024-07-02T13:21:20.957Z"}
{"level":"error","message":"\nInvalid `prisma.users.findFirst()` invocation:\n\n\nError querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"Cannot read properties of null (reading 'id')"}
{"level":"error","message":"Class constructor Response cannot be invoked without 'new'"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"products.findFirst","timestamp":"2024-07-02T13:30:55.061Z"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"products.findFirst","timestamp":"2024-07-02T13:31:08.266Z"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"products.findFirst","timestamp":"2024-07-02T13:31:20.119Z"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"products.findFirst","timestamp":"2024-07-02T13:31:45.763Z"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'","target":"products.findFirst","timestamp":"2024-07-02T13:31:53.509Z"}
{"level":"error","message":"\nInvalid `prisma.products.findFirst()` invocation:\n\n\nError in connector: Error querying the database: Server error: `ERROR 42000 (1226): User 'ulpfhoqykooqqi9k' has exceeded the 'max_user_connections' resource (current value: 5)'"}
